import { PlaceHolderImages } from './placeholder-images';

export type Service = {
  id: string;
  category: 'Cleaning' | 'Pest Control';
  name: string;
  description: string;
  base_price: number;
  rating: number;
  reviews: number;
  image_url: string;
  image_hint: string;
  features: string[];
};

export type SubCategory = {
  id: string;
  parentService: string;
  title: string;
  image: string;
  image_hint: string;
  rating: number;
  price: number;
  description?: string;
};

export type Category = {
  id: 'cleaning' | 'pest-control';
  name: 'Cleaning' | 'Pest Control';
  description: string;
};

export const categories: Category[] = [
  {
    id: 'cleaning',
    name: 'Cleaning',
    description: 'Comprehensive cleaning services for a spotless home.',
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    description: 'Effective solutions to keep your home pest-free.',
  },
];

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return image || { imageUrl: 'https://picsum.photos/seed/error/600/400', imageHint: 'placeholder' };
};

export const services: Service[] = [
  {
    id: 'bathroom-cleaning',
    category: 'Cleaning',
    name: 'Bathroom Cleaning',
    description: 'Deep cleaning of your bathroom, including tiles, fittings, and fixtures.',
    base_price: 499,
    rating: 4.8,
    reviews: 112000,
    image_url: getImage('bathroom-cleaning').imageUrl,
    image_hint: getImage('bathroom-cleaning').imageHint,
    features: [
      'Stain and spot removal from toilet, tiles, and basin',
      'Hard water stain removal',
      'Disinfection of surfaces',
    ],
  },
  {
    id: 'kitchen-cleaning',
    category: 'Cleaning',
    name: 'Kitchen Cleaning',
    description: 'Thorough cleaning of your kitchen, including appliances and cabinets.',
    base_price: 799,
    rating: 4.9,
    reviews: 98000,
    image_url: getImage('kitchen-cleaning').imageUrl,
    image_hint: getImage('kitchen-cleaning').imageHint,
    features: [
      'Oil and grease stain removal',
      'Appliance exterior cleaning (fridge, microwave)',
      'Cabinet and countertop cleaning',
    ],
  },
    {
    id: 'chimney-cleaning',
    category: 'Cleaning',
    name: 'Chimney Cleaning',
    description: 'Complete chimney cleaning services for a smoke-free kitchen.',
    base_price: 299,
    rating: 4.7,
    reviews: 55000,
    image_url: getImage('chimney-cleaning').imageUrl,
    image_hint: getImage('chimney-cleaning').imageHint,
    features: [
      'Removal of grease and oil',
      'Filter cleaning',
      'Motor and duct inspection',
    ],
  },
  {
    id: 'full-home-cleaning',
    category: 'Cleaning',
    name: 'Full Home / Move-in Cleaning',
    description: 'Complete top-to-bottom cleaning for your entire home.',
    base_price: 2499,
    rating: 4.9,
    reviews: 150000,
    image_url: getImage('full-home-cleaning').imageUrl,
    image_hint: getImage('full-home-cleaning').imageHint,
    features: [
      'Includes all rooms, kitchen, and bathrooms',
      'Dusting, vacuuming, and mopping',
      'Perfect for moving in or out',
    ],
  },
  {
    id: 'sofa-carpet-cleaning',
    category: 'Cleaning',
    name: 'Sofa & Carpet Cleaning',
    description: 'Professional cleaning to remove dust, stains, and allergens.',
    base_price: 399,
    rating: 4.7,
    reviews: 85000,
    image_url: getImage('sofa-carpet-cleaning').imageUrl,
    image_hint: getImage('sofa-carpet-cleaning').imageHint,
    features: [
      'Dry vacuuming to remove crumbs & dirt',
      'Wet shampooing & vacuuming for tough stains',
      'Safe for all fabric types',
    ],
  },
  {
    id: 'floor-tile-cleaning',
    category: 'Cleaning',
    name: 'Floor & Tile Cleaning',
    description: 'Restore the shine of your floors with professional scrubbing and polishing.',
    base_price: 599,
    rating: 4.8,
    reviews: 62000,
    image_url: getImage('floor-tile-cleaning').imageUrl,
    image_hint: getImage('floor-tile-cleaning').imageHint,
    features: [
      'Machine-assisted scrubbing',
      'Grout cleaning',
      'Suitable for marble, tiles, and wood',
    ],
  },
  {
    id: 'balcony-window-cleaning',
    category: 'Cleaning',
    name: 'Balcony / Window Cleaning',
    description: 'Streak-free cleaning for all your windows and glass surfaces.',
    base_price: 349,
    rating: 4.6,
    reviews: 45000,
    image_url: getImage('balcony-window-cleaning').imageUrl,
    image_hint: getImage('balcony-window-cleaning').imageHint,
    features: [
      'Interior and exterior window cleaning',
      'Grill and channel cleaning',
      'Safe and efficient process',
    ],
  },
  {
    id: 'mattress-cleaning',
    category: 'Cleaning',
    name: 'Mattress Cleaning',
    description: 'Sanitize your mattress and remove dust mites, allergens, and stains.',
    base_price: 499,
    rating: 4.7,
    reviews: 51000,
    image_url: getImage('mattress-cleaning').imageUrl,
    image_hint: getImage('mattress-cleaning').imageHint,
    features: [
      'Deep vacuuming and shampooing',
      'Stain and odor removal',
      'Kills bacteria and allergens',
    ],
  },
  {
    id: 'general-pest-control',
    category: 'Pest Control',
    name: 'Cockroach, Ant & General',
    description: 'Comprehensive treatment for common household pests.',
    base_price: 699,
    rating: 4.9,
    reviews: 210000,
    image_url: getImage('general-pest-control').imageUrl,
    image_hint: getImage('general-pest-control').imageHint,
    features: [
      'Herbal, low-odor gel application',
      'Targets hiding and breeding spots',
      'Safe for children and pets',
    ],
  },
  {
    id: 'bed-bugs-control',
    category: 'Pest Control',
    name: 'Bed Bugs Control',
    description: 'Intensive treatment to eradicate bed bugs from your home.',
    base_price: 899,
    rating: 4.8,
    reviews: 75000,
    image_url: getImage('bed-bugs-control').imageUrl,
    image_hint: getImage('bed-bugs-control').imageHint,
    features: [
      'Thorough inspection of furniture',
      'Advanced chemical spray treatment',
      'Follow-up visit included',
    ],
  },
  {
    id: 'termite-control',
    category: 'Pest Control',
    name: 'Termite Control',
    description: 'Protect your furniture and property from termite damage.',
    base_price: 1299,
    rating: 4.9,
    reviews: 95000,
    image_url: getImage('termite-control').imageUrl,
    image_hint: getImage('termite-control').imageHint,
    features: [
      'Drill-fill-seal technique',
      'Creates a chemical barrier',
      'Long-lasting protection',
    ],
  },
  {
    id: 'mosquito-control',
    category: 'Pest Control',
    name: 'Mosquito Control',
    description: 'Effective mosquito control for your home and surroundings.',
    base_price: 599,
    rating: 4.7,
    reviews: 68000,
    image_url: getImage('mosquito-control').imageUrl,
    image_hint: getImage('mosquito-control').imageHint,
    features: [
      'Indoor residual spray',
      'Outdoor fogging treatment',
      'Larvicidal treatment for stagnant water',
    ],
  },
];


export const subCategories: SubCategory[] = [
    // Bathroom Cleaning
    {
        id: 'bathroom-deep-cleaning',
        parentService: 'bathroom-cleaning',
        title: 'Full bathroom deep cleaning',
        image: getImage('full-bathroom-deep-cleaning').imageUrl,
        image_hint: getImage('full-bathroom-deep-cleaning').imageHint,
        rating: 4.9,
        price: 799,
    },
    {
        id: 'toilet-commode-cleaning',
        parentService: 'bathroom-cleaning',
        title: 'Toilet & commode cleaning',
        image: getImage('toilet-commode-cleaning').imageUrl,
        image_hint: getImage('toilet-commode-cleaning').imageHint,
        rating: 4.8,
        price: 349,
    },
    {
        id: 'sink-tap-descaling',
        parentService: 'bathroom-cleaning',
        title: 'Sink & tap descaling',
        image: getImage('sink-tap-descaling').imageUrl,
        image_hint: getImage('sink-tap-descaling').imageHint,
        rating: 4.7,
        price: 299,
    },
    {
        id: 'wall-tile-scrubbing',
        parentService: 'bathroom-cleaning',
        title: 'Wall & tile scrubbing',
        image: getImage('wall-tile-scrubbing').imageUrl,
        image_hint: getImage('wall-tile-scrubbing').imageHint,
        rating: 4.8,
        price: 399,
    },
    {
        id: 'shower-fittings-cleaning',
        parentService: 'bathroom-cleaning',
        title: 'Shower & fittings cleaning',
        image: getImage('shower-fittings-cleaning').imageUrl,
        image_hint: getImage('shower-fittings-cleaning').imageHint,
        rating: 4.7,
        price: 299,
    },
    {
        id: 'bathroom-floor-disinfecting',
        parentService: 'bathroom-cleaning',
        title: 'Bathroom floor disinfecting',
        image: getImage('bathroom-floor-disinfecting').imageUrl,
        image_hint: getImage('bathroom-floor-disinfecting').imageHint,
        rating: 4.9,
        price: 399,
    },
    {
        id: 'mirror-glass-cleaning',
        parentService: 'bathroom-cleaning',
        title: 'Mirror & glass cleaning',
        image: getImage('mirror-glass-cleaning').imageUrl,
        image_hint: getImage('mirror-glass-cleaning').imageHint,
        rating: 4.7,
        price: 249,
    },
    // Kitchen Cleaning
    {
        id: 'complete-kitchen-deep-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Complete kitchen deep cleaning',
        image: getImage('complete-kitchen-deep-cleaning').imageUrl,
        image_hint: getImage('complete-kitchen-deep-cleaning').imageHint,
        rating: 4.9,
        price: 1299,
    },
    {
        id: 'kitchen-chimney-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Chimney cleaning',
        image: getImage('chimney-cleaning').imageUrl,
        image_hint: getImage('chimney-cleaning').imageHint,
        rating: 4.8,
        price: 799,
    },
    {
        id: 'stove-burner-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Stove & burner cleaning',
        image: getImage('stove-burner-cleaning').imageUrl,
        image_hint: getImage('stove-burner-cleaning').imageHint,
        rating: 4.7,
        price: 399,
    },
    {
        id: 'kitchen-sink-tap-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Sink & tap cleaning',
        image: getImage('kitchen-sink-tap-cleaning').imageUrl,
        image_hint: getImage('kitchen-sink-tap-cleaning').imageHint,
        rating: 4.8,
        price: 299,
    },
    {
        id: 'tiles-backsplash-degreasing',
        parentService: 'kitchen-cleaning',
        title: 'Tiles & backsplash degreasing',
        image: getImage('tiles-backsplash-degreasing').imageUrl,
        image_hint: getImage('tiles-backsplash-degreasing').imageHint,
        rating: 4.8,
        price: 499,
    },
    {
        id: 'exhaust-fan-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Exhaust fan cleaning',
        image: getImage('exhaust-fan-cleaning').imageUrl,
        image_hint: getImage('exhaust-fan-cleaning').imageHint,
        rating: 4.7,
        price: 399,
    },
    {
        id: 'cabinet-cleaning',
        parentService: 'kitchen-cleaning',
        title: 'Cabinet interior & exterior cleaning',
        image: getImage('cabinet-cleaning').imageUrl,
        image_hint: getImage('cabinet-cleaning').imageHint,
        rating: 4.8,
        price: 599,
    },
    {
        id: 'refrigerator-microwave-exterior',
        parentService: 'kitchen-cleaning',
        title: 'Refrigerator & microwave exterior',
        image: getImage('refrigerator-microwave-exterior').imageUrl,
        image_hint: getImage('refrigerator-microwave-exterior').imageHint,
        rating: 4.7,
        price: 399,
    },
    // Full Home / Move-in Cleaning
    {
        id: '1bhk-full-home-cleaning',
        parentService: 'full-home-cleaning',
        title: '1BHK full home cleaning',
        image: getImage('1bhk-full-home-cleaning').imageUrl,
        image_hint: getImage('1bhk-full-home-cleaning').imageHint,
        rating: 4.9,
        price: 1999,
    },
    {
        id: '2bhk-full-home-cleaning',
        parentService: 'full-home-cleaning',
        title: '2BHK full home cleaning',
        image: getImage('2bhk-full-home-cleaning').imageUrl,
        image_hint: getImage('2bhk-full-home-cleaning').imageHint,
        rating: 4.9,
        price: 2499,
    },
    {
        id: '3bhk-full-home-cleaning',
        parentService: 'full-home-cleaning',
        title: '3BHK full home cleaning',
        image: getImage('3bhk-full-home-cleaning').imageUrl,
        image_hint: getImage('3bhk-full-home-cleaning').imageHint,
        rating: 4.8,
        price: 2999,
    },
    {
        id: 'villa-duplex-deep-cleaning',
        parentService: 'full-home-cleaning',
        title: 'Villa / Duplex deep cleaning',
        image: getImage('villa-duplex-deep-cleaning').imageUrl,
        image_hint: getImage('villa-duplex-deep-cleaning').imageHint,
        rating: 4.9,
        price: 3999,
    },
    {
        id: 'move-in-out-cleaning',
        parentService: 'full-home-cleaning',
        title: 'Move-in / Move-out cleaning',
        image: getImage('move-in-out-cleaning').imageUrl,
        image_hint: getImage('move-in-out-cleaning').imageHint,
        rating: 4.8,
        price: 3499,
    },
    {
        id: 'home-sanitization',
        parentService: 'full-home-cleaning',
        title: 'Home sanitization',
        image: getImage('home-sanitization').imageUrl,
        image_hint: getImage('home-sanitization').imageHint,
        rating: 4.9,
        price: 799,
    },
    {
        id: 'balcony-window-addon',
        parentService: 'full-home-cleaning',
        title: 'Balcony & window add-on',
        image: getImage('balcony-window-addon').imageUrl,
        image_hint: getImage('balcony-window-addon').imageHint,
        rating: 4.7,
        price: 499,
    },
    // Sofa & Carpet Cleaning
    {
        id: 'sofa-dry-vacuum-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Sofa dry vacuum cleaning',
        image: getImage('sofa-dry-vacuum-cleaning').imageUrl,
        image_hint: getImage('sofa-dry-vacuum-cleaning').imageHint,
        rating: 4.8,
        price: 499,
    },
    {
        id: 'sofa-shampoo-deep-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Sofa shampoo & deep cleaning',
        image: getImage('sofa-shampoo-deep-cleaning').imageUrl,
        image_hint: getImage('sofa-shampoo-deep-cleaning').imageHint,
        rating: 4.9,
        price: 699,
    },
    {
        id: 'carpet-dry-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Carpet dry cleaning',
        image: getImage('carpet-dry-cleaning').imageUrl,
        image_hint: getImage('carpet-dry-cleaning').imageHint,
        rating: 4.8,
        price: 399,
    },
    {
        id: 'carpet-deep-shampoo-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Carpet deep shampoo cleaning',
        image: getImage('carpet-deep-shampoo-cleaning').imageUrl,
        image_hint: getImage('carpet-deep-shampoo-cleaning').imageHint,
        rating: 4.9,
        price: 599,
    },
    {
        id: 'dining-chair-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Dining chair cleaning',
        image: getImage('dining-chair-cleaning').imageUrl,
        image_hint: getImage('dining-chair-cleaning').imageHint,
        rating: 4.7,
        price: 349,
    },
    {
        id: 'cushion-upholstery-cleaning',
        parentService: 'sofa-carpet-cleaning',
        title: 'Cushion & upholstery cleaning',
        image: getImage('cushion-upholstery-cleaning').imageUrl,
        image_hint: getImage('cushion-upholstery-cleaning').imageHint,
        rating: 4.8,
        price: 299,
    },
    // Floor & Tile Cleaning
    {
        id: 'floor-scrubbing-polishing',
        parentService: 'floor-tile-cleaning',
        title: 'Floor scrubbing & polishing',
        image: getImage('floor-scrubbing-polishing').imageUrl,
        image_hint: getImage('floor-scrubbing-polishing').imageHint,
        rating: 4.9,
        price: 699,
    },
    {
        id: 'tile-stain-removal',
        parentService: 'floor-tile-cleaning',
        title: 'Tile stain removal',
        image: getImage('tile-stain-removal').imageUrl,
        image_hint: getImage('tile-stain-removal').imageHint,
        rating: 4.8,
        price: 499,
    },
    {
        id: 'grout-line-deep-cleaning',
        parentService: 'floor-tile-cleaning',
        title: 'Grout line deep cleaning',
        image: getImage('grout-line-deep-cleaning').imageUrl,
        image_hint: getImage('grout-line-deep-cleaning').imageHint,
        rating: 4.7,
        price: 499,
    },
    {
        id: 'marble-granite-polishing',
        parentService: 'floor-tile-cleaning',
        title: 'Marble & granite polishing',
        image: getImage('marble-granite-polishing').imageUrl,
        image_hint: getImage('marble-granite-polishing').imageHint,
        rating: 4.8,
        price: 899,
    },
    {
        id: 'floor-sanitization',
        parentService: 'floor-tile-cleaning',
        title: 'Floor sanitization',
        image: getImage('floor-sanitization').imageUrl,
        image_hint: getImage('floor-sanitization').imageHint,
        rating: 4.9,
        price: 399,
    },
    // Balcony & Window Cleaning
    {
        id: 'balcony-full-cleaning',
        parentService: 'balcony-window-cleaning',
        title: 'Balcony full cleaning',
        image: getImage('balcony-full-cleaning').imageUrl,
        image_hint: getImage('balcony-full-cleaning').imageHint,
        rating: 4.9,
        price: 599,
    },
    {
        id: 'window-glass-cleaning',
        parentService: 'balcony-window-cleaning',
        title: 'Window glass cleaning',
        image: getImage('window-glass-cleaning').imageUrl,
        image_hint: getImage('window-glass-cleaning').imageHint,
        rating: 4.8,
        price: 399,
    },
    {
        id: 'window-grill-cleaning',
        parentService: 'balcony-window-cleaning',
        title: 'Window grill cleaning',
        image: getImage('window-grill-cleaning').imageUrl,
        image_hint: getImage('window-grill-cleaning').imageHint,
        rating: 4.7,
        price: 299,
    },
    {
        id: 'sliding-door-frame-cleaning',
        parentService: 'balcony-window-cleaning',
        title: 'Sliding door & frame cleaning',
        image: getImage('sliding-door-frame-cleaning').imageUrl,
        image_hint: getImage('sliding-door-frame-cleaning').imageHint,
        rating: 4.7,
        price: 349,
    },
    {
        id: 'balcony-railing-tiles-wash',
        parentService: 'balcony-window-cleaning',
        title: 'Balcony railing & tiles wash',
        image: getImage('balcony-railing-tiles-wash').imageUrl,
        image_hint: getImage('balcony-railing-tiles-wash').imageHint,
        rating: 4.8,
        price: 449,
    },
    // Mattress Cleaning
    {
        id: 'single-mattress-cleaning',
        parentService: 'mattress-cleaning',
        title: 'Single mattress cleaning',
        image: getImage('single-mattress-cleaning').imageUrl,
        image_hint: getImage('single-mattress-cleaning').imageHint,
        rating: 4.8,
        price: 499,
    },
    {
        id: 'double-mattress-cleaning',
        parentService: 'mattress-cleaning',
        title: 'Double mattress cleaning',
        image: getImage('double-mattress-cleaning').imageUrl,
        image_hint: getImage('double-mattress-cleaning').imageHint,
        rating: 4.9,
        price: 699,
    },
    {
        id: 'king-size-mattress-cleaning',
        parentService: 'mattress-cleaning',
        title: 'King size mattress cleaning',
        image: getImage('king-size-mattress-cleaning').imageUrl,
        image_hint: getImage('king-size-mattress-cleaning').imageHint,
        rating: 4.8,
        price: 899,
    },
    {
        id: 'vacuum-shampoo-cleaning',
        parentService: 'mattress-cleaning',
        title: 'Vacuum & shampoo cleaning',
        image: getImage('vacuum-shampoo-cleaning').imageUrl,
        image_hint: getImage('vacuum-shampoo-cleaning').imageHint,
        rating: 4.8,
        price: 499,
    },
    {
        id: 'mattress-sanitization',
        parentService: 'mattress-cleaning',
        title: 'Mattress sanitization',
        image: getImage('mattress-sanitization').imageUrl,
        image_hint: getImage('mattress-sanitization').imageHint,
        rating: 4.9,
        price: 599,
    },
    // Pest Control - Cockroach, Ant & General
    {
        id: '1bhk-pest-control',
        parentService: 'general-pest-control',
        title: '1BHK pest control',
        image: getImage('1bhk-pest-control').imageUrl,
        image_hint: getImage('1bhk-pest-control').imageHint,
        rating: 4.8,
        price: 799,
    },
    {
        id: '2bhk-pest-control',
        parentService: 'general-pest-control',
        title: '2BHK pest control',
        image: getImage('2bhk-pest-control').imageUrl,
        image_hint: getImage('2bhk-pest-control').imageHint,
        rating: 4.9,
        price: 999,
    },
    {
        id: '3bhk-pest-control',
        parentService: 'general-pest-control',
        title: '3BHK pest control',
        image: getImage('3bhk-pest-control').imageUrl,
        image_hint: getImage('3bhk-pest-control').imageHint,
        rating: 4.9,
        price: 1199,
    },
    {
        id: 'kitchen-bathroom-targeted-treatment',
        parentService: 'general-pest-control',
        title: 'Kitchen & bathroom targeted treatment',
        image: getImage('kitchen-bathroom-targeted-treatment').imageUrl,
        image_hint: getImage('kitchen-bathroom-targeted-treatment').imageHint,
        rating: 4.8,
        price: 699,
    },
    {
        id: 'full-home-pest-control-general',
        parentService: 'general-pest-control',
        title: 'Full home pest control',
        image: getImage('full-home-pest-control-general').imageUrl,
        image_hint: getImage('full-home-pest-control-general').imageHint,
        rating: 4.9,
        price: 1499,
    },
    // Bed Bugs Control
    {
        id: 'bedroom-bed-bug-treatment',
        parentService: 'bed-bugs-control',
        title: 'Bedroom bed bug treatment',
        image: getImage('bedroom-bed-bug-treatment').imageUrl,
        image_hint: getImage('bedroom-bed-bug-treatment').imageHint,
        rating: 4.8,
        price: 999,
    },
    {
        id: 'full-home-bed-bug-control',
        parentService: 'bed-bugs-control',
        title: 'Full home bed bug control',
        image: getImage('full-home-bed-bug-control').imageUrl,
        image_hint: getImage('full-home-bed-bug-control').imageHint,
        rating: 4.9,
        price: 1499,
    },
    {
        id: 'mattress-heat-spray-treatment',
        parentService: 'bed-bugs-control',
        title: 'Mattress heat & spray treatment',
        image: getImage('mattress-heat-spray-treatment').imageUrl,
        image_hint: getImage('mattress-heat-spray-treatment').imageHint,
        rating: 4.8,
        price: 799,
    },
    {
        id: 'bed-bugs-follow-up-session',
        parentService: 'bed-bugs-control',
        title: 'Follow-up session',
        image: getImage('bed-bugs-follow-up-session').imageUrl,
        image_hint: getImage('bed-bugs-follow-up-session').imageHint,
        rating: 4.7,
        price: 499,
    },
    // Termite Control
    {
        id: 'pre-construction-anti-termite',
        parentService: 'termite-control',
        title: 'Pre-construction anti-termite',
        image: getImage('pre-construction-anti-termite').imageUrl,
        image_hint: getImage('pre-construction-anti-termite').imageHint,
        rating: 4.9,
        price: 2499,
    },
    {
        id: 'post-construction-termite-control',
        parentService: 'termite-control',
        title: 'Post-construction termite control',
        image: getImage('post-construction-termite-control').imageUrl,
        image_hint: getImage('post-construction-termite-control').imageHint,
        rating: 4.9,
        price: 1999,
    },
    {
        id: 'furniture-termite-spray',
        parentService: 'termite-control',
        title: 'Furniture termite spray',
        image: getImage('furniture-termite-spray').imageUrl,
        image_hint: getImage('furniture-termite-spray').imageHint,
        rating: 4.8,
        price: 999,
    },
    {
        id: 'wooden-door-wardrobe-treatment',
        parentService: 'termite-control',
        title: 'Wooden door & wardrobe treatment',
        image: getImage('wooden-door-wardrobe-treatment').imageUrl,
        image_hint: getImage('wooden-door-wardrobe-treatment').imageHint,
        rating: 4.8,
        price: 799,
    },
    {
        id: 'full-home-termite-protection',
        parentService: 'termite-control',
        title: 'Full home termite protection',
        image: getImage('full-home-termite-protection').imageUrl,
        image_hint: getImage('full-home-termite-protection').imageHint,
        rating: 4.9,
        price: 2499,
    },
    // Mosquito Control
    {
        id: 'indoor-mosquito-spray-treatment',
        parentService: 'mosquito-control',
        title: 'Indoor mosquito spray treatment',
        image: getImage('indoor-mosquito-spray-treatment').imageUrl,
        image_hint: getImage('indoor-mosquito-spray-treatment').imageHint,
        rating: 4.8,
        price: 799,
    },
    {
        id: 'outdoor-fogging-service',
        parentService: 'mosquito-control',
        title: 'Outdoor fogging service',
        image: getImage('outdoor-fogging-service').imageUrl,
        image_hint: getImage('outdoor-fogging-service').imageHint,
        rating: 4.9,
        price: 999,
    },
    {
        id: 'full-home-mosquito-control',
        parentService: 'mosquito-control',
        title: 'Full home mosquito control',
        image: getImage('full-home-mosquito-control').imageUrl,
        image_hint: getImage('full-home-mosquito-control').imageHint,
        rating: 4.8,
        price: 1199,
    },
    {
        id: 'herbal-mosquito-treatment',
        parentService: 'mosquito-control',
        title: 'Herbal mosquito treatment',
        image: getImage('herbal-mosquito-treatment').imageUrl,
        image_hint: getImage('herbal-mosquito-treatment').imageHint,
        rating: 4.7,
        price: 899,
    },
    {
        id: 'monthly-maintenance-plan',
        parentService: 'mosquito-control',
        title: 'Monthly maintenance plan',
        image: getImage('monthly-maintenance-plan').imageUrl,
        image_hint: getImage('monthly-maintenance-plan').imageHint,
        rating: 4.8,
        price: 1499,
    },
    // Chimney Cleaning (from previous request, now integrated with kitchen)
    {
        id: 'chimney-deep-cleaning',
        parentService: 'chimney-cleaning',
        title: 'Deep chimney cleaning',
        image: getImage('chimney-deep-cleaning').imageUrl,
        image_hint: getImage('chimney-deep-cleaning').imageHint,
        rating: 4.8,
        price: 899,
    },
    {
        id: 'chimney-filter-mesh',
        parentService: 'chimney-cleaning',
        title: 'Filter & mesh cleaning',
        image: getImage('chimney-filter-mesh').imageUrl,
        image_hint: getImage('chimney-filter-mesh').imageHint,
        rating: 4.6,
        price: 499,
    },
    {
        id: 'chimney-oil-collector',
        parentService: 'chimney-cleaning',
        title: 'Oil collector cleaning',
        image: getImage('chimney-oil-collector').imageUrl,
        image_hint: getImage('chimney-oil-collector').imageHint,
        rating: 4.7,
        price: 399,
    },
    {
        id: 'chimney-motor-cleaning',
        parentService: 'chimney-cleaning',
        title: 'Motor cleaning & lubrication',
        image: getImage('chimney-motor-cleaning').imageUrl,
        image_hint: getImage('chimney-motor-cleaning').imageHint,
        rating: 4.5,
        price: 699,
    },
    {
        id: 'chimney-complete-service',
        parentService: 'chimney-cleaning',
        title: 'Complete chimney service',
        image: getImage('chimney-complete-service').imageUrl,
        image_hint: getImage('chimney-complete-service').imageHint,
        rating: 4.9,
        price: 1199,
    },
    {
        id: 'chimney-inspection',
        parentService: 'chimney-cleaning',
        title: 'Chimney inspection (basic check)',
        image: getImage('chimney-inspection').imageUrl,
        image_hint: getImage('chimney-inspection').imageHint,
        rating: 4.4,
        price: 299,
    },
    {
        id: 'chimney-duct-cleaning',
        parentService: 'chimney-cleaning',
        title: 'Duct cleaning',
        image: getImage('chimney-duct-cleaning').imageUrl,
        image_hint: getImage('chimney-duct-cleaning').imageHint,
        rating: 4.7,
        price: 649,
    },
    {
        id: 'chimney-installation',
        parentService: 'chimney-cleaning',
        title: 'Installation & re-fitting',
        image: getImage('chimney-installation').imageUrl,
        image_hint: getImage('chimney-installation').imageHint,
        rating: 4.6,
        price: 899,
    },
];
